### ISSUE TITLE
Importer doesn't work with premium rulebook

### ISSUE THREAD

**Issue by chrpow** [chrpow/shadowdark-pdf-importer#11]
The importer cannot import monsters from the premium version of the rulebook PDF.

**Comment by chrpow** [comment]
This is a very low priority because 1. I don't own the premium rulebook, and 2. It seems like everyone with the premium rulebook also has access to the regular rulebook. Importing the regular rulebook should give you all the same information without issue.

**Comment by nschoenwald** [comment]
I ordered the premium version after the kickstarter. I only have access to the premium version pdf. Is there really no chance of this being added? I would love to import the monsters into foundry.

**Comment by chrpow** [comment]
> I ordered the premium version after the kickstarter. I only have access to the premium version pdf. Is there really no chance of this being added? I would love to import the monsters into foundry.

Unless someone who owns the premium rulebook submits a pull request, this won't be addressed. But the full rulebook is going to be added to the base Foundry system in the next update anyway.
