### ISSUE TITLE
Multiple versions of the core rulebook seem to exist

### ISSUE THREAD

**Issue by chrpow** [chrpow/shadowdark-pdf-importer#12]
The importer is currently designed to work with version 4.8 of the core rulebook. There are apparently multiple different versions of "version 4.8" floating around the Internet. The different versions have different page counts, and therefore can't be processed the same way.

**Comment by chrpow** [comment]
If you are experiencing this problem, try downloading the very latest PDF from The Arcane Library's official website, even if it matches your current version number.

**Comment by chrpow** [comment]
Potential fix: Account for both 3 and 4 page offsets.

**Comment by develroo** [comment]
I just redownloaded another copy from ArcaneLib and it is showing 4.7? Where did you get 4.8 from ?

**Comment by chrpow** [comment]
4.8 is the version I downloaded last year from the Kickstarter. Unfortunately, there's not a great way for me to implement different versions, as I can only work with the versions that I personally own. Thankfully, all monsters, items, and spells from the core rulebook are going to be added into the base foundry system in the next update, so this won't be a problem for long. I won't be making any updates to the core rulebook importer before then because they'll become immediately obsolete.

**Comment by develroo** [comment]
No idea how you got a different version from the released one, but as you say, that content should be rolled into foundry sooner rather than later, so point is rather moot.
