### ISSUE TITLE
Unable to import Letters_from_the_Dark_Vol._III_Tales_of_the_Fey.pdf

### ISSUE THREAD

**Issue by develroo** [chrpow/shadowdark-pdf-importer#13]
Just downloaded this from Drivethru.

```
pdfinfo  Letters_from_the_Dark_Vol._III_Tales_of_the_Fey.pdf 
Title:           shadowdark-a5-template
Producer:        PDFlib+PDI 9.1.1p3 (PHP7/Linux-x86_64)
CreationDate:    Tue Mar 26 15:53:39 2024 GMT
Custom Metadata: no
Metadata Stream: no
Tagged:          no
UserProperties:  no
Suspects:        no
Form:            none
JavaScript:      no
Pages:           64
Encrypted:       yes (print:yes copy:yes change:no addNotes:yes algorithm:AES)
Page size:       419.528 x 595.276 pts
Page rot:        0
File size:       69276896 bytes
Optimized:       no
PDF version:     1.7
```

No logs in Fvtt bu the error shows. 

![Screenshot from 2024-03-26 16-24-26](https://github.com/chrpow/shadowdark-pdf-importer/assets/7777993/60effe1d-7309-4435-a7dd-24d6b10ef72f)

As I mentioned in the other issue,  The Core Rules are 4.7 and that is what is downloaded from Arcane lib.

Edit. Oh forgot to mention both 

"Letters from the Dark Vol. II: Slayer's Moon_V1-3.pdf"
'Letters from the Dark Vol. I: Out of Time.pdf'

Load fine. So odd the 3rd one complains.

**Comment by chrpow** [comment]
Hey, first off, thanks for purchasing my zines!

LFTD3 hasn't been input into the code yet. I will try to take care of that today or tomorrow. The PDFs have to be hard-coded into the importer module by me, so they won't automatically be compatible with the module upon release.

**Comment by develroo** [comment]
Fairy nuff. 

Might want to think of a way to scan the PDF for common features instead of hand-picking them, though. Looking for PDF properties of white text on a black banner seem to be a common refrain. 

Even 3rd party modules like Elven Tower keep that sort of style. 

![Screenshot from 2024-03-27 15-10-52](https://github.com/chrpow/shadowdark-pdf-importer/assets/7777993/1e4dcdd1-dc19-4bd5-abac-48278a0861b9)

**Comment by chrpow** [comment]
Supported by Release 0.0.7
