### ISSUE TITLE
Import button does not show up

### ISSUE THREAD

**Issue by oakes123** [chrpow/shadowdark-pdf-importer#14]
I installed the module and it shows as enabled.   I have also restarted the server.

When I go to the configure tab (gears) there is no button for importing

**Comment by oakes123** [comment]
Here's an image...
![Uploading Screenshot 2024-03-31 at 8.28.01 AM.png…]()

**Comment by oakes123** [comment]
<img width="1148" alt="Screenshot 2024-03-31 at 8 28 01 AM" src="https://github.com/chrpow/shadowdark-pdf-importer/assets/60296308/c1c2d946-7bcb-498f-b29a-38c60068b9b4">

**Comment by chrpow** [comment]
Hi, are you playing on Forge? Others have reported that something in Forge prevents the module from working.

**Comment by oakes123** [comment]
Yes I am.  I’ll see if I can get any info from the Forge Discord.  Thank you!

**Comment by oakes123** [comment]
I got some help on the Forge Discord.  Best guess is that the module version number may not have been updated and so Forge has an older version cached in their online marketplace.

If I install from manifest (https://github.com/chrpow/shadowdark-pdf-importer/releases/latest/download/module.json) then it works correctly.

**Comment by chrpow** [comment]
> I got some help on the Forge Discord. Best guess is that the module version number may not have been updated and so Forge has an older version cached in their online marketplace.
> 
> If I install from manifest (https://github.com/chrpow/shadowdark-pdf-importer/releases/latest/download/module.json) then it works correctly.

Glad it worked out. I don't know how the Forge marketplace works - I've never even used Forge, so I don't know how my module showed up on their marketplace. It's good this is recorded in an issue, now anyone who searches can find out that this is the solution.
