### ISSUE TITLE
Pdf Importer does not appear on Forge

### ISSUE THREAD

**Issue by marquesarthur** [chrpow/shadowdark-pdf-importer#18]
> This is a module that imports content from Shadowdark PDFs directly into Foundry. Once installed and enabled, go to the "Game Settings" (gear icon) and click "Shadowdark PDF Importer." From there, select a supported PDF and click "Import PDF." That's it!

When I click gear icon:

![forge-error](https://github.com/chrpow/shadowdark-pdf-importer/assets/1497480/d75c88f0-522b-4259-ae8d-ef729b1ee809)

My modules:

![modules](https://github.com/chrpow/shadowdark-pdf-importer/assets/1497480/144b4080-5b03-44df-8f55-fdf64408407c)

**Comment by chrpow** [comment]
This is a known issue with Forge (see #14). Supposedly it can be fixed by downloading the module directly from https://github.com/chrpow/shadowdark-pdf-importer/releases/latest/download/module.json.

I don't personally have Forge, so I don't have a way to test this or troubleshoot it.
